AirlineProject.Web/AirlineProject.Web/Controllers/PlaneController.cs
using AirlineProject.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AirlineProject.Web.Controllers
{
    public class PlaneController : Controller
    {
        private readonly PlaneDAO planeDAO = new PlaneDAO();
        // GET: PlaneController
        public ActionResult Index()
        {

            IEnumerable<Plane> mplanes = planeDAO.GetPlanes();
            List<Plane> model = new List<Plane>();

            foreach (var plane in mplanes)
            {
                Plane temp = new Plane()
                {
                    id = plane.id,
                    name = plane.name,
                    capacity = plane.capacity

                };

                model.Add(temp);

            }
            return View(model);
        }

        // GET: PlaneController/Details/5
        public ActionResult Details(int id)
        {
            Plane plane = planeDAO.GetPlane(id);
            return View(plane);
        }

        // GET: PlaneController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Plane plane)
        {
            if (ModelState.IsValid)
            {
                Plane newPlane = new Plane();
                newPlane.id = plane.id;
                newPlane.name = plane.name;
                newPlane.capacity = plane.capacity;


                planeDAO.AddPlane(newPlane);

                return RedirectToAction("Index");
            }

            return View(plane);
        }

        // GET: PlaneController/Edit/5
        public ActionResult Edit(int id)
        {
            Plane plane = planeDAO.GetPlane(id);
            return View(plane);
        }

        // POST: PlaneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind] Plane plane)
        {
            if (ModelState.IsValid)
            {
                Plane newPlane = new Plane();

                newPlane.id = plane.id;
                newPlane.name = plane.name;
                newPlane.capacity = plane.capacity;


                planeDAO.UpdatePlane(newPlane);

                return RedirectToAction("Index");
            }

            return View(plane);
        }

        // GET: PlaneController/Delete/5
        public ActionResult Delete(int id)
        {
            Plane plane = planeDAO.GetPlane(id);
            return View(plane);
        }

        // POST: PlaneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Plane plane = planeDAO.GetPlane(id);
                planeDAO.DeletePlane(plane.id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AirlineProject.Web/AirlineProject.Web/Views/Plane/Create.cshtml
@model AirlineProject.Data.Plane

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-light">Create</h1>

<h4 class="text-light">Plane</h4>
<hr />
<div class="row text-light">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="capacity" class="control-label"></label>
                <input asp-for="capacity" class="form-control" />
                <span asp-validation-for="capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Plane/Delete.cshtml
@model AirlineProject.Data.Plane

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-light">Delete</h1>

<h3 class="text-light">Are you sure you want to delete this?</h3>
<div class="text-light">
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.capacity)
        </dd>
    </dl>
    
    <form class="text-light" asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="text-light" asp-action="Index">Back to List</a>
    </form>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Plane/Details.cshtml
@model AirlineProject.Data.Plane

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-light">Details</h1>

<div class="text-light">
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.capacity)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }, new { style = "color: white" }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.id }, new { style = "color: white" }) | 
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Plane/Edit.cshtml
@model AirlineProject.Data.Plane

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-light">Edit</h1>

<h4 class="text-light">Plane</h4>
<hr />
<div class="row text-light">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="capacity" class="control-label"></label>
                <input asp-for="capacity" class="form-control" />
                <span asp-validation-for="capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Plane/Index.cshtml
@model IEnumerable<AirlineProject.Data.Plane>

@{
    ViewData["Title"] = "Planes";
}


<html style="height: 100%">
<body style="background: linear-gradient(135deg, #9b76d7 10%, #0f12b7 100%)">
    <div>
        <h1 class="text-light">Our Fleet</h1>
        <a class="navbar-brand text-light" asp-area="" asp-controller="Plane" asp-action="Create">New Plane</a>
        <table class="table table-hover text-light">
            <thead>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.id)</td>
                    <td>@Html.DisplayNameFor(model => model.name)</td>
                    <td>@Html.DisplayNameFor(model => model.capacity)</td>
                    <td>Detalis</td>

                </tr>
            </thead>
            <tbody>
                @foreach (var plane in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelitem => plane.id)</td>
                        <td>@Html.DisplayFor(modelitem => plane.name)</td>
                        <td>@Html.DisplayFor(modelitem => plane.capacity)</td>

                        <td>@Html.ActionLink("Details", "Details", new { id = plane.id }, new { style = "color: white" })</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>