AirlineProject.Web/AirlineProject.Web/Controllers/PassengerController.cs
using AirlineProject.Data;
using AirlineProject.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AirlineProject.Web.Controllers
{
    public class PassengerController : Controller
    {
        private readonly IPassengerDAO passengerDAO;
        private readonly IFlightDAO flightDAO;

        public PassengerController(IPassengerDAO passengerdao)
        {
            this.passengerDAO = passengerdao;
        }

        // GET: PassengerController
        public IActionResult Index()
        {
            IEnumerable<Passenger> mpassengers = passengerDAO.GetPassengers();
            List<Passenger> model = new List<Passenger>();

            foreach(var passenger in mpassengers)
            {
                Passenger temp = new Passenger()
                {
                    id = passenger.id,
                    name = passenger.name,
                    email = passenger.email,
                    dob = passenger.dob,
                    jobTitle = passenger.jobTitle,
                    confirmationNumber = passenger.confirmationNumber
                    
                };

                model.Add(temp);

            }
            return View(model);
        }

        // GET: PassengerController/Details/5
        public ActionResult Details(int id)
        {
            Passenger model = passengerDAO.GetPassenger(id);
            return View(model);
        }
        [HttpGet]
        // GET: PassengerController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: PassengerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Passenger passenger)
        {
            if(passenger.HowFull(passenger.flight.id) < passenger.CheckCapacity(passenger.flight.id))
            {
                if (ModelState.IsValid)
                {
                    Passenger newPassenger = new Passenger();
                    newPassenger.name = passenger.name;
                    newPassenger.id = passenger.id;
                    newPassenger.email = passenger.email;
                    newPassenger.dob = passenger.dob;
                    newPassenger.confirmationNumber = passenger.confirmationNumber;

                    passengerDAO.AddPassenger(passenger);

                    return RedirectToAction("Index");

                }
            }
            return View(passenger);
        }

        // GET: PassengerController/Edit/5
        public ActionResult Edit(int id)
        {
            Passenger model = passengerDAO.GetPassenger(id);
            return View(model);
        }

        // POST: PassengerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind]Passenger passenger)
        {
            if (ModelState.IsValid)
            {
                Passenger newPassenger = new Passenger();
                newPassenger.name = passenger.name;
                newPassenger.id = passenger.id;
                newPassenger.email = passenger.email;
                newPassenger.dob = passenger.dob;
                newPassenger.confirmationNumber = passenger.confirmationNumber;

                passengerDAO.UpdatePassenger(passenger);

                return RedirectToAction("Index");

            }
            return View(passenger);
        }

        // GET: PassengerController/Delete/5
        public ActionResult Delete(int id)
        {
            Passenger model = passengerDAO.GetPassenger(id);

            return View(model);
        }

        // POST: PassengerController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Passenger passenger = passengerDAO.GetPassenger(id);
                passengerDAO.DeletePassenger(passenger.id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AirlineProject.Web/AirlineProject.Web/Views/Passenger/Create.cshtml
@model AirlineProject.Data.Passenger

@{
    ViewData["Title"] = "Create";
 }

<h1 class="text-light">Add a New Passenger</h1>

<h4 class="text-light">Passenger</h4>
<hr />
<div class="row text-light">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="name" class="conrol-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dob" class="conrol-label"></label>
                <input asp-for="dob" class="form-control" />
                <span asp-validation-for="dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="conrol-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="jobTitle" class="conrol-label"></label>
                <input asp-for="jobTitle" class="form-control" />
                <span asp-validation-for="jobTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="flight.id" class="conrol-label"></label>
                <input asp-for="flight.id" class="form-control" />
                <span asp-validation-for="flight.id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>

    </div>

</div>

<div>
    <a class="text-light" asp-action="Index">Back to Passengers</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Passenger/Delete.cshtml
@model AirlineProject.Data.Passenger

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-light">Delete</h1>

<h3 class="text-light">Are you sure you want to delete this?</h3>
<div class="text-light">
    <h4>Passenger</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dob)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.jobTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.jobTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.confirmationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.confirmationNumber)
        </dd>
    </dl>
    
    <form class="text-light" asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="text-light" asp-action="Index">Back to List</a>
    </form>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Passenger/Details.cshtml
@model AirlineProject.Data.Passenger

@{ 
    ViewData["Title"] = "Details";
}

<h1 class="text-light">Details</h1>

<div class="text-light">
    <h4>Passenger</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dob)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.dob)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.jobTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.jobTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.confirmationNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.confirmationNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.flight.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.flight.id);
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.flight.departureAirport)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.flight.departureAirport)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.flight.arrivalAirport)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.flight.arrivalAirport)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.flight.departureTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.flight.departureTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.flight.arrivalTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.flight.arrivalTime)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }, new { style = "color: white" }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.id }, new { style = "color: white" }) |
    <a class="text-light" asp-action="Index">Back to Passengers</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Passenger/Edit.cshtml
@model AirlineProject.Data.Passenger

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-light">Edit</h1>

<h4 class="text-light">Passenger</h4>
<hr />
<div class="row text-light">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dob" class="control-label"></label>
                <input asp-for="dob" class="form-control" />
                <span asp-validation-for="dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="jobTitle" class="control-label"></label>
                <input asp-for="jobTitle" class="form-control" />
                <span asp-validation-for="jobTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="flight.id" class="control-label"></label>
                <input asp-for="flight.id" class="form-control" />
                <span asp-validation-for="flight.id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class = "text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Passenger/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
    @model IEnumerable<AirlineProject.Data.Passenger>
@{
    ViewData["Title"] = "Passengers";
}

<html style="height: 100%">
<body style="background: linear-gradient(135deg, #9b76d7 10%, #0f12b7 100%)">
    <div>
        <h2 class="text-light">View all Passengers</h2>
        <a class="navbar-brand text-light" asp-area="" asp-controller="Passenger" asp-action="Create">New Passenger</a>
        <table class="table table-hover text-light">
            <thead>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.name)</td>
                    <td>@Html.DisplayNameFor(model => model.email)</td>
                    <td>@Html.DisplayNameFor(model => model.dob)</td>
                    <td>@Html.DisplayNameFor(model => model.jobTitle)</td>
                    <td>@Html.DisplayNameFor(model => model.confirmationNumber)</td>
                    <td>Details</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var passenger in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelitem => passenger.name)</td>
                        <td>@Html.DisplayFor(modelitem => passenger.email)</td>
                        <td>@Html.DisplayFor(modelitem => passenger.dob)</td>
                        <td>@Html.DisplayFor(modelitem => passenger.jobTitle)</td>
                        <td>@Html.DisplayFor(modelitem => passenger.confirmationNumber)</td>
                        <td>@Html.ActionLink("Details", "Details", new { id = passenger.id }, new { style = "color: white" })</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>