AirlineProject.Web/AirlineProject.Web/Controllers/PilotController.cs
using AirlineProject.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AirlineProject.Web.Controllers
{
    public class PilotController : Controller
    {
        private readonly PilotDAO pilotDAO = new PilotDAO();
        // GET: PilotController
        public ActionResult Index()
        {
            IEnumerable<Pilot> mpilots = pilotDAO.GetPilots();
            List<Pilot> model = new List<Pilot>();

            foreach (var pilot in mpilots)
            {
                Pilot temp = new Pilot()
                {
                    id = pilot.id,
                    name = pilot.name,
                    email = pilot.email
                };

                model.Add(temp);

            }
            return View(model);
        }

        // GET: PilotController/Details/5
        public ActionResult Details(int id)
        {
            Pilot model = pilotDAO.GetPilot(id);
            return View(model);
        }

        // GET: PilotController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: PilotController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Pilot pilot)
        {
            if (ModelState.IsValid)
            {
                Pilot newPilot = new Pilot();
                newPilot.id = pilot.id;
                newPilot.name = pilot.name;
                newPilot.email = pilot.email;

                
                pilotDAO.AddPilot(newPilot);
                
                
                return RedirectToAction("Index");
            }

            return View(pilot);
        }

        // GET: PilotController/Edit/5
        public ActionResult Edit(int id)
        {
            Pilot model = pilotDAO.GetPilot(id);
            return View(model);
        }

        // POST: PilotController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind] Pilot pilot)
        {
            if (ModelState.IsValid)
            {
                Pilot newPilot = new Pilot();
                newPilot.id = pilot.id;
                newPilot.name = pilot.name;
                newPilot.email = pilot.email;

                pilotDAO.UpdatePilot(newPilot);
                return RedirectToAction("Index");
            }
            return View(pilot);
        }

        // GET: PilotController/Delete/5
        public ActionResult Delete(int id)
        {
            Pilot pilot = pilotDAO.GetPilot(id);
            return View(pilot);
        }

        // POST: PilotController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Pilot pilot = pilotDAO.GetPilot(id);
                pilotDAO.DeletePilot(pilot.id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AirlineProject.Web/AirlineProject.Web/Views/Pilot/Create.cshtml
@model AirlineProject.Data.Pilot

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-light">Create</h1>

<h4 class="text-light">Pilot</h4>
<hr />
<div class="row text-light">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Pilot/Delete.cshtml
@model AirlineProject.Data.Pilot

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-light">Delete</h1>

<h3 class="text-light">Are you sure you want to delete this?</h3>
<div class="text-light">
    <h4>Pilot</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="text-light" asp-action="Index">Back to List</a>
    </form>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Pilot/Details.cshtml
@model AirlineProject.Data.Pilot

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-light">Details</h1>

<div class="text-light">
    <h4>Pilot</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }, new { style = "color: white" }) |
    @Html.ActionLink("Delete", "Delete", new {  id = Model.id}, new { style = "color: white" }) | 
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Pilot/Edit.cshtml
@model AirlineProject.Data.Pilot

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-light">Edit</h1>

<h4 class="text-light">Pilot</h4>
<hr />
<div class="row text-light">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Pilot/Index.cshtml
@model IEnumerable<AirlineProject.Data.Pilot>

@{
    ViewData["Title"] = "Pilots";
}

<html style="height: 100%">
<body style="background: linear-gradient(135deg, #9b76d7 10%, #0f12b7 100%)">
    <div>
        <h2 class="text-light">Meet Our Pilots!</h2>
        <a class="navbar-brand text-light" asp-area="" asp-controller="Pilot" asp-action="Create">New Pilot</a>
        <table class="table table-hover text-light">
            <thead>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.name)</td>
                    <td>@Html.DisplayNameFor(model => model.email)</td>
                    <td>Details</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var pilot in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelitem => pilot.name)</td>
                        <td>@Html.DisplayFor(modelitem => pilot.email)</td>

                        <td>@Html.ActionLink("Details", "Details", new { id = pilot.id }, new { style = "color: white" })</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>