AirlineProject.Web/AirlineProject.Web/Controllers/FlightController.cs
using AirlineProject.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AirlineProject.Web.Controllers
{
    public class FlightController : Controller
    {
        private readonly FlightDAO flightDAO = new FlightDAO();
        // GET: FlightController
        public ActionResult Index()
        {
            
            IEnumerable<Flight> mflights = flightDAO.GetFights();
            List<Flight> model = new List<Flight>();

            foreach (var flight in mflights)
            {
                Flight temp = new Flight()
                {
                    id = flight.id,
                    departureAirport = flight.departureAirport,
                    arrivalAirport = flight.arrivalAirport,
                    departureTime = flight.departureTime,
                    arrivalTime = flight.arrivalTime,
                    pilot = flight.pilot,
                    plane = flight.plane
                    

                };

                model.Add(temp);

            }
            return View(model);
        }

        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {
            Flight flight = flightDAO.GetFlight(id);
            return View(flight);
        }

        // GET: FlightController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Flight flight)
        {
            if (ModelState.IsValid)
            {
                Flight newFlight = new Flight();
                newFlight.id = flight.id;
                newFlight.departureAirport = flight.departureAirport;
                newFlight.arrivalAirport = flight.arrivalAirport;
                newFlight.departureTime = flight.departureTime;
                newFlight.arrivalTime = flight.arrivalTime;
                newFlight.plane = flight.plane;
                newFlight.pilot = flight.pilot;

                flightDAO.AddFlight(newFlight);

                return RedirectToAction("Index");
            }
            return View(flight);
        }

        // GET: FlightController/Edit/5
        public ActionResult Edit(int id)
        {
            Flight flight = flightDAO.GetFlight(id);
            return View(flight);
        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind] Flight flight)
        {
            if (ModelState.IsValid)
            {
                Flight newFlight = new Flight();
                newFlight.id = flight.id;
                newFlight.departureAirport = flight.departureAirport;
                newFlight.arrivalAirport = flight.arrivalAirport;
                newFlight.departureTime = flight.departureTime;
                newFlight.arrivalTime = flight.arrivalTime;
                newFlight.plane = flight.plane;
                newFlight.pilot = flight.pilot;

                flightDAO.UpdateFlight(newFlight);

                return RedirectToAction("Index");
            }
            return View(flight);
        }

        // GET: FlightController/Delete/5
        public ActionResult Delete(int id)
        {
            Flight flight = flightDAO.GetFlight(id);
            return View(flight);
        }

        // POST: FlightController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Flight flight = flightDAO.GetFlight(id);
                flightDAO.DeleteFlight(flight.id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AirlineProject.Web/AirlineProject.Web/Views/Flight/Create.cshtml
@model AirlineProject.Data.Flight

@{
    ViewData["Title"] = "Create";
}
<html style="height: 100%">
<body style="background: linear-gradient(135deg, #9b76d7 10%, #0f12b7 100%)">
    <h1 class="text-light">Create</h1>

    <h4 class="text-light">Flight</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group text-light">
                    <label asp-for="arrivalTime" class="control-label"></label>
                    <input asp-for="arrivalTime" class="form-control" />
                    <span asp-validation-for="arrivalTime" class="text-danger"></span>
                </div>
                <div class="form-group text-light">
                    <label asp-for="departureTime" class="control-label"></label>
                    <input asp-for="departureTime" class="form-control" />
                    <span asp-validation-for="departureTime" class="text-danger"></span>
                </div>
                <div class="form-group text-light">
                    <label asp-for="departureAirport" class="control-label"></label>
                    <input asp-for="departureAirport" class="form-control" />
                    <span asp-validation-for="departureAirport" class="text-danger"></span>
                </div>
                <div class="form-group text-light">
                    <label asp-for="arrivalAirport" class="control-label"></label>
                    <input asp-for="arrivalAirport" class="form-control" />
                    <span asp-validation-for="arrivalAirport" class="text-danger"></span>
                </div>
                <div class="form-group text-light">
                    <label asp-for="plane.id" class="control-label"></label>
                    <input asp-for="plane.id" class="form-control" />
                    <span asp-validation-for="plane.id" class="text-danger"></span>
                </div>
                <div class="form-group text-light">
                    <label asp-for="pilot.id" class="control-label"></label>
                    <input asp-for="pilot.id" class="form-control" />
                    <span asp-validation-for="pilot.id" class="text-danger"></span>
                </div>
                <div class="form-group text-light">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a class ="text-light" asp-action="Index">Back to List</a>
    </div>

</body>
</html>

AirlineProject.Web/AirlineProject.Web/Views/Flight/Delete.cshtml
@model AirlineProject.Data.Flight

@{
    ViewData["Title"] = "Delete";
}


    <h1 class="text-light">Delete</h1>

    <h3 class="text-light">Are you sure you want to delete this flight?</h3>
    <div class="text-light">
        <h4>Flight</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.arrivalTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.arrivalTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.departureTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.departureTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.departureAirport)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.departureAirport)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.arrivalAirport)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.arrivalAirport)
            </dd>
        </dl>

        <form class ="text-light"asp-action="Delete">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>

AirlineProject.Web/AirlineProject.Web/Views/Flight/Details.cshtml
@model AirlineProject.Data.Flight

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-light">Details</h1>

<div class="text-light">
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.arrivalTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.arrivalTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.departureTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.departureTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.departureAirport)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.departureAirport)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.arrivalAirport)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.arrivalAirport)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.plane.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.plane.name)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }, new { style = "color: white" }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.id }, new { style = "color: white" }) | 
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Flight/Edit.cshtml
@model AirlineProject.Data.Flight

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-light">Edit</h1>

<h4 class="text-light">Flight</h4>
<hr />
<div class="row text-light">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="arrivalTime" class="control-label"></label>
                <input asp-for="arrivalTime" class="form-control" />
                <span asp-validation-for="arrivalTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departureTime" class="control-label"></label>
                <input asp-for="departureTime" class="form-control" />
                <span asp-validation-for="departureTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departureAirport" class="control-label"></label>
                <input asp-for="departureAirport" class="form-control" />
                <span asp-validation-for="departureAirport" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="arrivalAirport" class="control-label"></label>
                <input asp-for="arrivalAirport" class="form-control" />
                <span asp-validation-for="arrivalAirport" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="plane.id" class="control-label"></label>
                <input asp-for="plane.id" class="form-control" />
                <span asp-validation-for="plane" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pilot.id" class="control-label"></label>
                <input asp-for="pilot.id" class="form-control" />
                <span asp-validation-for="pilot.id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="text-light">
    <a class = "text-light" asp-action="Index">Back to List</a>
</div>

AirlineProject.Web/AirlineProject.Web/Views/Flight/Index.cshtml
@model IEnumerable<AirlineProject.Data.Flight>

@{
    ViewData["Title"] = "Flights";
}

    <h1 class="text-light">Flights</h1>

    <div>
        <a class="navbar-brand text-light" asp-area="" asp-controller="Flight" asp-action="Create">New Flight</a>
        <table class="table table-hover text-light">
            <thead>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.id)</td>
                    <td>@Html.DisplayNameFor(model => model.arrivalAirport)</td>
                    <td>@Html.DisplayNameFor(model => model.departureAirport)</td>
                    <td>@Html.DisplayNameFor(model => model.departureTime)</td>
                    <td>@Html.DisplayNameFor(model => model.arrivalTime)</td>
                    <td>@Html.DisplayNameFor(model => model.plane)</td>
                    <td>@Html.DisplayNameFor(model => model.pilot)</td>
                    <td>Details</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var flight in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelitem => flight.id)</td>
                        <td>@Html.DisplayFor(modelitem => flight.arrivalAirport)</td>
                        <td>@Html.DisplayFor(modelitem => flight.departureAirport)</td>
                        <td>@Html.DisplayFor(modelitem => flight.departureTime)</td>
                        <td>@Html.DisplayFor(modelitem => flight.arrivalTime)</td>
                        <td>@Html.DisplayFor(modelitem => flight.plane.name)</td>
                        <td>@Html.DisplayFor(modelitem => flight.pilot.name)</td>

                        <td>@Html.ActionLink("Details", "Details", new { id = flight.id }, new { style = "color: white" })</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>